_posts/2019-06-06-best-firmware-size-tools.md

Up to you, I found your terminal prefixes very distracting and it made it difficult to find the actual command you were trying to point out. 
If you do want to show the folder, maybe show explicit `cd` commands.

Remove extra terminal prefixes, fix incomplete sentence

---

_config.yml
_includes/footer.html
_includes/head.html
_plugins/range-excerpt.rb
feed.xml
index.html
readme.md

Adressed Issues:
- The RSS Icon in the browser wouldn't allow me to subscribe (linked to non-existent ATOM feed).
- Posts only showed excerpts (seems intentional) without clear communication that there would be more content.
- I couldn't click the title of a post, because the URL would contain leading and trailing semantic whitespace -> invalid URL (`%20%20%20%20%20%20https://...`).
- I couldn't copy the RSS URL easily since it was a relative URL instead of an absolute URL.
- Many fields weren't escaped properly.
Changes:
- Move custom excerpt logic into a plugin.
- Remove semantic whitespace.
- Escape all the fields.
- Fix `<link>`

RSS Feed Fixes

---

404.md
_includes/head.html
_posts/2019-07-09-get-the-most-out-of-the-linker-map-file.md
_sass/base.scss
_sass/custom.scss
_sass/layout.scss
_sass/typography.scss

Something I had in my stash:
- Revert link color, unbold links, underline links. Tends improve accessibility (since convention) and also is less distracting while reading an article.
- Use a monospaced font from Google Fonts for code.
- Tweaked everything to follow a vertical grid (`0.25rem` increments) for a better visual rhythm. Also increased line-height for regular paragraphs to provide more negative whitespace (more airy).

Tweak styling

---

_sass/layout.scss

In a previous change, we added `margin-left: 1.5em` on all `li,ul`
elements. Unfortunately, the post lists use `ul` so this master change
applied to every listing of posts too and now the website looks worse on
mobile.
Here we add special formatting for post lists to remove that global (and
generally sensible) margin

Remove Post list margin on left

---

example/debugging-asserts/Makefile

Before:
```
$ make
...
Linking library
ld: interrupt/example/debugging-asserts/build/main.o: in function `prv_main_path_A':
interrupt/example/debugging-asserts/main.c:19: undefined reference to `assert_path_A'
ld: interrupt/example/debugging-asserts/main.c:21: undefined reference to `assert_path_B'
collect2: error: ld returned 1 exit status
make: *** [interrupt/example/debugging-asserts/build/nrf52.elf] Error 1
```
After:
```
$ make
Makefile:46: *** IMPL is not set to a valid assert implementation.  Stop.
```

Show an error if IMPL is invalid

---

_posts/2019-05-21-gdb-for-firmware-1.md
_posts/2019-06-06-best-firmware-size-tools.md
_posts/2019-07-16-fix-bugs-and-secure-firmware-with-the-mpu.md
_posts/2019-07-30-bluetooth-low-energy-a-primer.md
_posts/2019-08-06-a-deep-dive-into-arm-cortex-m-debug-interfaces.md
_posts/2019-09-04-arm-cortex-m-exceptions-and-nvic.md
_posts/2019-09-17-continuous-integration-for-firmware.md
_posts/2019-09-24-ble-throughput-primer.md
_posts/2019-10-08-unit-testing-basics.md
_posts/2019-10-22-best-and-worst-gcc-clang-compiler-flags.md
_posts/2019-10-30-cortex-m-rtos-context-switching.md
_posts/2019-11-20-cortex-m-fault-debug.md

In our image links we were not prefixing with a `/`. This meant if
someone navigated to a blog post and had a `/` at the end of the url,
the image would be searched for the wrong location
i.e
https://interrupt.memfault.com/blog/cortex-m-fault-debug/
would result in a lookup of `img/cortex-m-fault/cfsr.png` resolving to:
https://interrupt.memfault.com/blog/cortex-m-fault-debug/img/cortex-m-fault/cfsr.png
We need to prefix all of our image urls with a '/' so the search for
the image is always relative to the [root of the
website](https://www.w3schools.com/html/html_filepaths.asp)
This change updates all the urls ...
`rg "\[.*\]\(img" -l | xargs -I {} gsed -i "s|](img/|](/img/|g" {}`

Make all links to the img directory root-relative

---

_config.yml
_includes/head.html
_includes/header-custom.html
_layouts/tag.html
_sass/base.scss
_sass/tag.scss
css/main.scss
index.html
tags.html

Inspired from [here](https://codinfox.github.io/dev/2015/03/06/use-tags-and-categories-in-your-jekyll-based-github-pages/)

Expose a tag page for easier discovery of articles about particular topics

---

_config.yml

I noticed after I added a bunch of source files to the example folder that
Jekyll was trying to *build* these files, and running a `make` in the
example directory was causing a very long rebuild.
After some exploration, it appears there's an `exclude` option we should be
using to exclude some of the folders.
https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml
I used to see build times times from around 20-30s, now I see 2-6 seconds.
Woo!

Improve Jekyll build time

---

_posts/2019-04-25-getting-started-with-ibdap-and-atsamd21g18.md
_posts/2019-05-14-zero-to-main-1.md
_posts/2019-05-21-gdb-for-firmware-1.md
_posts/2019-06-06-best-firmware-size-tools.md
_posts/2019-06-25-how-to-write-linker-scripts-for-firmware.md
_posts/2019-07-02-automate-debugging-with-gdb-python-api.md
_posts/2019-07-09-get-the-most-out-of-the-linker-map-file.md
_posts/2019-07-16-fix-bugs-and-secure-firmware-with-the-mpu.md
_posts/2019-07-30-bluetooth-low-energy-a-primer.md
_posts/2019-08-06-a-deep-dive-into-arm-cortex-m-debug-interfaces.md
_posts/2019-08-13-how-to-write-a-bootloader-from-scratch.md
_posts/2019-09-04-arm-cortex-m-exceptions-and-nvic.md
_posts/2019-09-17-continuous-integration-for-firmware.md
_posts/2019-09-24-ble-throughput-primer.md
_posts/2019-10-22-best-and-worst-gcc-clang-compiler-flags.md
_posts/2019-10-30-cortex-m-rtos-context-switching.md
_posts/2019-11-12-boostrapping-libc-with-newlib.md
_posts/2019-11-20-cortex-m-fault-debug.md
_posts/2019-12-11-reproducible-firmware-builds.md
_posts/2019-12-17-zero-to-main-rust-1.md
_posts/2020-01-07-conda-developer-environments.md
_posts/2020-02-04-rust-for-digital-signal-processing.md
_posts/2020-02-11-improving-compilation-times-c-cpp-projects.md

When we were originally writing posts for Interrupt, we left a lot of
breadcrumbs like "In a future post...". Now that we've been at it for a
while, we've written a lot of these posts, so I've went ahead and added
links between most of the posts and to series (tags).
Also, while I'm at it, remove all hard-coded interrupt.memfault.com links
and change them to use `post_url` since these are harder to test.
Test Plan:
- Mostly go over the diff by hand/eyes
- Go through each post and make sure the links that I've edited render
correctly and properly link to another page.

Add internal linking for older posts

---

.gitmodules
_posts/2020-03-23-intro-to-renode.md
example/renode/.gitignore
example/renode/Makefile
example/renode/Makefile_renode_example.mk

* Twiddled example project for more auto-magic setup (no submodule dep, no need to prebuild libopencm3)
* Minor typo fixes and a little extra verbiage in some areas I got confused in
I didn't add a note about it but one hiccup I ran into with the renode mac startup script was not having realpath installed (not sure where its supposed to come from) so I just did:
```
cat ~/mybin/realpath
python -c "import os; print(os.path.realpath('$1'))"
```

Misc edits to renode post

---

_includes/author-social.html
_layouts/author.html
_layouts/post.html
_plugins/authors.rb
authors.html
index.html

I love Chris and Francois' posts, and I want a way to read all of them
easier.
```
/authors - All authors and posts page
/authors/<author_id> - Individual author page
```

Add Author pages that show the short bio and posts

---

_posts/2019-09-24-ble-throughput-primer.md

While I was reading [Ble throughput Primer](https://interrupt.memfault.com/blog/ble-throughput-primer) I noticed that there were some images missing. This PR aims to fix that.

Fix wrong image path in BLE primer post

---

readme.md

While reading the official README file, I found out that Code of Conduct and Contributing section were not accesible. This change fixes that.

Fix links on readme

---

_posts/2020-06-02-profiling-firmware-on-cortex-m.md

Same behavior described in https://github.com/memfault/interrupt/pull/116, this time at [Profiling Firmware on Cortex-M](https://interrupt.memfault.com/blog/profiling-firmware-on-cortex-m)

Fix wrong image path in Profiling Firmware post

---

_posts/2020-06-09-firmware-shell.md

I think you missed this closing brace in the markup for a link  (thanks for the great article!)

fix markup typo in 2020-06-09-firmware-shell.md

---

_sass/layout.scss
_sass/tag.scss

The following PR aims to improve several sections at Interrupt Blog which I list below: 
- **Pagination items**
Up to now, if some relentless embedded engineer wants to dive into one of your great articles probably will end it up using the pagination tool, however, when this is made at small screens this is what we have:
I propose to change the css a little bit to provide enough space having this instead: 
- **Space between tags**
I suggest to increase the space between tags when is viewed from small screens, what we have right now is: 
But we can have this:
- **Footer overlapping main content**
From small screens as well I noticed that footer gets in the middle at the bottom of main content. See the following: 
We can add a little modification on code to separate footer and main content …

Improving theme

---

_sass/custom.scss
contributing.md

At [contributing](https://interrupt.memfault.com/blog/contributing) page we have the following behavior:
And when this is seen from small screens, this is what we got: 
In last image, user needs to scroll to the right having to see that form isn't wrapped into the main container.
What I suggest is make the iframe responsive, so that user can scroll it without extending the page width. It will look like the following:

Make contributing form responsive

---

_posts/2020-01-22-i2c-in-a-nutshell.md

While reading through the "I2C in a Nutshell" post I noticed an error in the waveform under the section titled "I2C Address Issues".
The Acknowledge-bit in the example waveform is supposed to be in the in the NACK state but is a 0, the ACK state. So I've corrected it in the waveform. I'm pretty sure NACK == 1, and ACK == 0, but I am new to I2C :D 
Thanks for the great article :)

Set acknowledge bit to 'NACK' in I2C Address Issues

---

.gitignore
_config.yml
_posts/2020-09-16-cortex-m-watchpoints.md

What a great article @chrisc11 congrats :D While reading it I found out some catchs. 
I think we can hide the build folder that it's created from example folder? I am not sure if `build` name folder is used for all entire examples. What do you think? 
Aside of that, it looks like an image wasn't pushed to the repo?
On the top of that, I've enable compressed option so instead of loading the css files with comments and in that way we can speed up load process on the site.

Faster Debugging with Watchpoints

---

_includes/head.html

Needed to add `<meta name="referrer"
content="no-referrer-when-downgrade">` according to the comment post:
https://meta.discourse.org/t/no-referer-no-embedding/163524/4
Also needed to adjust admin embedded settings as the post above
describes.

Discourse comment embedded fix

---

_posts/2020-10-20-advanced-gdb.md

The hyperlinks for the last two links don't seem to be clickable

Make anchor tag links clickable

---

_includes/share-buttons.html
_plugins/url_encode.rb

Replacing `'` with nothing wasn't the right approach. Just need to URL encode the items. Unfortunately no `url_encode` built in. I think it may be in a future Jekyll version though?

Fix urlencoding post titles for social links

---

_posts/2019-06-25-how-to-write-linker-scripts-for-firmware.md
_posts/2019-10-30-cortex-m-rtos-context-switching.md
_posts/2020-12-08-seamless-firmware-with-platformio.md

while reading, i found some typo's.
i also saw an unfinished sentence at https://interrupt.memfault.com/blog/how-to-write-linker-scripts-for-firmware, just below the "Variables" section: "In the first post, our ResetHandler relied on seemingly magic variables to know the address of each of our sections of memory. It turns out, those variable came" [unfinished], but don't have a suggestion for content.
thanks for writing and publishing interrupt!

fix some typo's in posts

---

_posts/2021-01-19-release-versioning.md

Adds a missing 'C' to change a rogue 'PATH' into the 'PATCH' that I'm sure was intended
P.S. Thanks for another great article ;)

Fix minor typo in 2021-01-19-release-versioning.md

---

_posts/2019-07-23-using-pypi-packages-with-GDB.md
_posts/2019-11-20-cortex-m-fault-debug.md

Hello interrupters!
Here are some changes that I find relevant to update during my readings. 
The first commit I guess is self explanatory. 
On the second one I would love to hear your thoughts on this. [PyCortexMDebug](https://github.com/bnahill/PyCortexMDebug ) has been pushing some code that don't allow to run it over python 2. This make that steps shown about this package at  https://interrupt.memfault.com/blog/cortex-m-fault-debug article won't work. 
Assuming that we are using python 2 coming coming from https://interrupt.memfault.com/blog/automate-debugging-with-gdb-python-api I guess may somehow let the embedded developer know that checking out from cortex-m-fault-debug master won't work. So, I added a new line to checkout to the latest commit that actually works.
I'm not aware if …

Tiny changes on posts

---

example/breakpoint/Makefile
example/debugmon/Makefile

Hi, I find this blog by accident and learn a lot from here. When I try to compile the example demo of `breakpoint ` and `debugmon` I get a error message at link stage.The error information is here:
```
Linking library
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libc.a(lib_a-abort.o): in function `abort':
/build/newlib-CVVEyx/newlib-3.3.0/build/arm-none-eabi/thumb/v7e-m+fp/hard/newlib/libc/stdlib/../../../../../../../../newlib/libc/stdlib/abort.c:59: undefined reference to `_exit'
```
My platform information:
```
kernel version: 5.8.0-28
gcc version: arm-none-eabi-gcc(15:9-2019-q4-0ubuntu1) 9.2.1 20191025(release)
```
After some search I found that is because these demo use some function …

fix libc symbol not defined compile error

---

_config.yml
_includes/pagination.html
_layouts/default.html
_layouts/split-view.html

Hello 👋
I noticed that the blog page count has been increasing. Because of that, the pagination is starting to look overwhelming. Not that it looks bad at it's current state, but as the page count increases it will become overpopulated with page number buttons.
_Current_
---
I have found a better solution for pagination. 
I took the inspiration from the following sources:
* https://dribbble.com/shots/2351417-What-s-your-fav-pagination (example number 7)
* https://uxframework.pearson.com/c/pagination (Standard pagination)
* https://codemyui.com/pagination-ux-pure-css/
Here's how it works:
The structure is as follows:
`[Previous page] [First page number] ... (N trailing) [Current page] (N leading) ... [Last page number] [Next page]`
There is a new option in **_config.yml** file called …

Improved pagination UX

---

_posts/2019-07-02-automate-debugging-with-gdb-python-api.md
_posts/2019-07-16-fix-bugs-and-secure-firmware-with-the-mpu.md
_posts/2019-09-04-arm-cortex-m-exceptions-and-nvic.md
_posts/2019-10-30-cortex-m-rtos-context-switching.md
_posts/2019-11-20-cortex-m-fault-debug.md

Change the box text on each of the above pages to say:
If you'd rather listen to me present this information and see some demos in action, watch this webinar recording.
Interested in learning more about debugging HardFaults? watch this webinar recording.
Could you also add those same text boxes to these posts:
https://interrupt.memfault.com/blog/automate-debugging-with-gdb-python-api
https://interrupt.memfault.com/blog/fix-bugs-and-secure-firmware-with-the-mpu

[Webinar recording] few updates

---

example/firmware-shell/complex/shell/src/shell.c

Successive backspace can break `rx_buffer` by making `rx_size` nagetive. I added if statement to prevent this.

Prevent underflow by many backspaces in firmware-shell

---

example/mcuboot/bootloader/Makefile

This commit sets mcu boot repository used in example to a state where
the porting code implemented here is able to compile. The reason why
doing this is that, mcu boot so far has introduced several changes
that are missing in example. This will allow to compile the code right
away.

post: example: mcuboot: freeze mcuboot to specific version

---

Dockerfile
build.sh
entrypoint.sh
interrupt-cli
interrupt-server.sh
readme.md

One of the great features that come with Interrupt is the fact that there are different authors that share their experiences along a diverse set of embedded topics. I think that to write an article, the embedded developer should clone an instance of interrupt blog and set up a jekyll local server. This imply to install all required packages on local machine but wouldn't be great if we can have a way to support a dockerize interrupt version so that embedded developers, if they already have docker installed, can take advantage of this and start creating their article drafts over the container? 
For that I've created a draft PR that contain the changes to be made on repo in order to build an interrupt docker image and write the drafts article over the container.
It would be great to read …

Dockerize interrupt

---

_posts/2019-08-13-how-to-write-a-bootloader-from-scratch.md
_posts/2021-11-23-noinit-memory.md

Typo in the example on message passing, thanks @vpetrigo and @v-barshaw
for finding it!
Also update the noinit article with a reference to this example.
Fixes #171.

Fix typo in how-to-write-a-bootloader-from-scratch

---

_posts/2021-10-27-pre-commit.md
example/pre-commit/.pre-commit-config.yaml

Add a few additional general notes on using clang-format.
Also update the pre-commit example config repo versions (`pre-commit
autoupdate`).

Update pre-commit hints about clang-format

---

_posts/2020-12-15-defensive-and-offensive-programming.md

Added to CTA blocks to the top and bottom of the article linking to the upcoming offensive programming webinar similar to the CTA blocks

Add Webinar CTA blocks to top & bottom of article

---

_posts/2021-11-23-noinit-memory.md

```
main.c:15:35: error: expected ')' before 'volatile'
15 | __attribute__((section(".noinit")) volatile int my_non_initialized_integer;
|                                   ^~~~~~~~~
|                                   )
```
```
$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.07) 10.3.1 20210621 (release)
```

Fix unbalanced parens in noinit example code

---

_posts/2020-01-22-i2c-in-a-nutshell.md

I fixed a small typo in the 'I2C in a nutshell' post.

Fixed small typo in I2C post

---

_posts/2022-03-30-dealing-with-large-symbol-files.md

@noahp, another great post! 
It seems that some file extension accidentally slipped into some of the snippets which led me to think I skipped a paragraph or something. But me thinks those are just artifacts from editing.

Remove confusing file extensions in some snippets

---

example/renode/renode-config.resc
example/renode/tests/test-button.robot

Renode changed the name of the UART peripherals from `uartx` to `usartx`, which breaks the Renode example. This PR changes `uart2` to `usart2`.

Renode peripheral name changed from uart2 to usart2

---

_posts/2021-10-07-cmsis-packs.md

On my mac the cmsis-pack-manager path had a space in it.  `/Users/devin/Library/Application Support/cmsis-pack-manager`.

Quote cmsis pack manager path

---

example/fwup-architecture/gpio.c
example/fwup-architecture/usart.c

I've been looking at fwup-architecture and fwup-signing examples. I know these example were tested with Renode but I've noticed that USART2 isn't setup correctly for receiving.

USART2 RX not configured correctly in fwup example code

---

Dockerfile
entrypoint.sh
interrupt-server.sh
readme.md

Update to a more recent ruby version (2.7->3.0), which is necessary to
support the lunr.js jekyll plugin dep `therubyracer`.
Minor tweaks to the run script and image build, and push to docker hub.

Update docker image

---

Gemfile
Gemfile.lock
netlify.toml

This is updating the lunr.js plugin to do two things:
1. Use a libv8 library that works on Mac. This was already done in the
'master' branch of the plugin, so we just update to the latest
master.
2. Fix the large amount of JSON nesting by setting max_nesting to false.
---
Error:
```
Installing libv8 3.16.14.19 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /Users/tyler/dev/memfault/interrupt/vendor/bundle/ruby/2.7.0/gems/libv8-3.16.14.19/ext/libv8
/Users/tyler/.rbenv/versions/2.7.5/bin/ruby -I /Users/tyler/.rbenv/versions/2.7.5/lib/ruby/2.7.0 -r ./siteconf20230103-55676-1bomqs8.rb
extconf.rb
creating Makefile
/Users/tyler/dev/memfault/interrupt/vendor/bundle/ruby/2.7.0/gems/libv8-3.16.14.19/ext/libv8/builder.rb:86:in …
```

Update lunr.js plugin to latest to use different libv8

---

Gemfile
Gemfile.lock
netlify.toml

It's super slow! so make it only run when the
`GENERATE_SEARCH_INDEX=true` environment variable is set.
See
https://github.com/memfault/jekyll-lunr-js-search/commit/4db4cab461594a92022430fd75442747494f4160
for the change that implements this in the lunr-js jekyll plugin fork.

Make lunr.js index gen opt-in

---

Gemfile
Gemfile.lock
_includes/script.html
netlify.toml

In #315 I made the lunr.js search index generation opt-in via the
environment variable `GENERATE_SEARCH_INDEX`, but did not add a check
for the missing index file in that case, and that results in an error
when the page is loaded:
```
[2023-05-09 16:20:42] ERROR `/js/search.min.js' not found.
```
Update our forked plugin and the scripts template to omit the script for
non-production build; switch to the built-in environment variable
`JEKYLL_ENV` which is available to Liquid template expressions.

Fix annoying message when search index is missing

---

readme.md

This flag causes jekyll to not regenerate the page index which causes new posts to not show up in the blog list.
After further investigation, this behavior is known and documented: https://jekyllrb.com/docs/configuration/incremental-regeneration/

Amend README to remove the --incremental option when running locally

---

_layouts/homepage.html

The "Welcome to Memfault!" text on the landing page was deemed a bit
wordy, and suggested to be removed.

style: remove "welcome to" on landing page

---

_posts/2023-07-19-embedded-async-rust.md

Fix issues with a missing link body, as well as a mistake with using
back-tick for a lifetime parameter.

fix: async rust rendering issues

---

_posts/2023-07-26-monitoring-battery-life.md

Just a small spelling error fix on the latest battery post

fix connectivity spelling error on battery post

---

.github/workflows/detect-renamed-posts.js
.github/workflows/detect-renamed-posts.yml

See it catch the error here:
https://github.com/memfault/interrupt/actions/runs/5825914834/job/15798644392#step:4:9
See it pass when a redirect is included here:
https://github.com/memfault/interrupt/actions/runs/5826059210/job/15799126175#step:4:5

Add github action to check for redirects on rename

---

requirements.txt

When reading through some old Interrupt articles, I noticed a bunch of block diagrams were not rendering.
For example, `blog/device-firmware-update-cookbook` would fail on multiple diagrams with messages like:
```
Rendering Failed: blockdiag -T svg --nodoctype /tmp/input20230824-6359-57l5w2 -o /tmp/output20230824-6359-1mps6hh.svg: ERROR: 'ImageDraw' object has no attribute 'textsize'
```
And the output in the terminal was failing with `   Jekyll Diagrams: Rendering Failed: blockdiag -T svg --nodoctype /var/folders/dz/5g4qmn_56lvcrd_mkswhf2w80000gn/T/input20230828-86743-6tj8l6 -o /var/folders/dz/5g4qmn_56lvcrd_mkswhf2w80000gn/T/output20230828-86743-uql6re.svg: ERROR: 'FreeTypeFont' object has no attribute 'getsize' `
I found this issue on `blockdiag`'s GitHub page, indicating that the …

Force Pillow to stay at version 9.5.0 to prevent failing renders

---

.github/workflows/detect-ruby-version-mismatch.yml
readme.md

Plus a GitHub workflow to make sure the `README` and `.ruby-version` are in sync 😎 
Can be tested by running the workflow manually:
```
gh workflow run detect-ruby-version-mismatch.yml --ref $(git rev-parse --abbrev-ref HEAD)
```
Tested by checking for failure when either the `README` or the `.ruby-version` was changed and there was a mismatch. Checked for success by reverting each change. Results are [here](https://github.com/memfault/interrupt/actions/workflows/detect-ruby-version-mismatch.yml).
Sadly didn't know re-named workflows generate a new workflow and [can't get removed](https://github.com/orgs/community/discussions/26256)...so there is an extra workflow in [Actions](https://github.com/memfault/interrupt/actions) from when I renamed the workflow that I've disabled for now.

Add more guidance on Ruby

---

_posts/2023-09-06-july-2023-roundup.md

A few comments/questions:
- As always, can I please ask for a spot check to ensure I've divided up the URLs under the correct headings? 
- Noah and François both shared articles about packet sniffers and both mention Wireshark, but I *think* these are still two separate projects. Is that right? And I have François' share under "Articles & Learnings" but Noah's under "Projects & Tools". Should both be under "Projects & Tools"?
- I noticed after I committed that there is a "(4)" in the beginning of the YouTube link title, which needs to be removed (first share under "Articles & Learnings".
- I wrote a few of the descriptions for some of the links; if you think they could be more interesting or make a better point, then please feel free to change!
One more thing: all this year the title of …

Create July 2023 Roundup

---

_posts/2023-09-13-hardware-actor-scheduler.md

A relative path used to point to source code on GitHub worked when navigating
from GitHub, but doesn't work when accessed from a different domain name, i.e.
memfault.com. The link is now the full GitHub URL.
Tested manually with local build.

Fix broken link to source code

---

_posts/2023-11-01-october-2023-roundup.md

- Added 4 articles (last 4 under Articles & Learning) as we needed to bulk up. Can you let me know if any of them should be pulled/any descriptions are off? 
- Should this be listed under articles & learning or projects & tools? (Not sure if it’s a project) https://popovicu.com/posts/789-kb-linux-without-mmu-riscv/
- Same. asabove^ - is this in the right section under articles or should be a tool? - [**Linkable Loadable Extensions (LLEXT) — Zephyr Project Documentation**](https://docs.zephyrproject.org/latest/services/llext/index.html)<br>
- Is this ugly/better way to show this (first article)?
* [UBfuzz: Finding Bugs in Sanitizer Implementations](https://shao-hua-li.github.io/files/2024_ASPLOS_UBFUZZ.pdf) Detecting bugs in sanitizers with a fuzz- based approach. The caption below stuck …

Create October 2023 Roundup

---

_posts/2024-01-04-december-2023-roundup.md

SO MUCH EASIER with all the contributions and notes! Wow, what a difference. 😀
PS: If it still seems a bit short, I can add 2 newer articles that have technically been shared in January by Tyler and Noah.
I'm probably tired or maybe it's because it was easier, but I feel like I'm second-guessing myself on a couple of seemingly obvious things; please see my notes below. 
- Most notably, I think my intro line needs to go - Lol I was laughing when I wrote it, but I don't think I'll find myself as amusing after some sleep. :) But do we want to include anything capturing some of the highlights of 2023 from [this email sent to subscribers last week](http://memfault-8551838.hs-sites.com/inside-look-2023-with-interrupt), or keep it simple, as it has been in previous years?  
- I'm leaning towards …

Create December 2023 Roundup

---

_posts/2024-01-10-practical_zephyr_basics.md

Also tweaks the title and adds some grammar changes.

content: publish zephyr basics article

---

_posts/2024-01-24-practical_zephyr_kconfig.md

- Adjusted grammar and punctuation for clarity
- Adjusted some spacing found by a markdown linter --> should look at adding this to a pre-commit hook!

content: publish zephyr kconfig article

---

_posts/2023-11-08-device-reliability-metrics.md

Update references from crashiness to stability

Rename crashiness to stability

---

_posts/2023-08-09-a-modern-c-dev-env.md

This is just a little update for the GitHub actions mentioned in the article. I updated the reference repository already, and those should be the matching changes in the article.

Update GitHub action versions in C Development Environment article

---

_posts/2020-05-20-arm-cortexm-with-llvm-clang.md

Hi, this blog post was really useful but missing this information took me way too long to research! I have seen this issue with clang-10 (as used in the post) and clang-16 (latest). This issue is mentioned in the comments of the post and the `gcc` default on non-Darwin platforms is in the docs (https://clang-analyzer.llvm.org/scan-build.html) if you search for "Darwin".
This would have saved me a lot of time and presumably will help people in the future!

Helpful note for running scan-build

---

_includes/submit-pr.html

Adjust language to say "submit PR on our GitHub" instead of "at GitHub"

fix: adjust submit PR banner

---

_config_preview.yml
cloudflare_build.sh

This will enable our Cloudflare builder to publish posts that are in the
future and not yet published on our production build
```
JEKYLL_BUILD_CONFIG_PARAM=",_config_preview.yml"
bundle exec jekyll build --config _config.yml${JEKYLL_BUILD_CONFIG_PARAM}
```
For production, JEKYLL_BUILD_CONFIG_PARAM will be empty
For preview, JEKYLL_BUILD_CONFIG_PARAM will contain the above value.
Wrap this into a cloudflare_build.sh script that is used by Cloudflare
to build

Create a `_config_preview.yml` for preview builds

---

_posts/2024-03-29-diving-into-jtag-part-4.md

There is a minor grammar issue in the article excerpt. This PR fixes it.
Visual check.

fix(grammar): fix minor typo in jtag part 4

---

example/pre-commit/.pre-commit-config.yaml

Fixes https://github.com/memfault/interrupt/issues/456 as suggested also here: https://github.com/home-assistant/core/issues/86892#issuecomment-1407641288
By bumping `isort` version `5.10.1` to `5.12.0 `

Isort version bump in pre-commit-config (fixes #456)

---

_posts/2021-10-27-pre-commit.md
example/pre-commit/.pre-commit-config.yaml
example/pre-commit/ruff.toml

From #457, use `ruff` in place of `isort` + `black`. Also update the pre-commit article with the same.

Update pre-commit article and example

---

_data/notifications.yml

We have a panel coming up on May 7th. This PR adds a notification to
the site.
Additionally removed the `title` field of the notification since
it was not being used in the html `_includes/notifications.html` for
rendering the banner.
Manually checked banner and link.

banner: add notification for upcoming panel

---

_data/notifications.yml

Remove the banner advertising today's panel.
Verified banner is gone in preview

chore: remove panel notification banner

---

_posts/2024-05-08-eoss-recap.md

There are a few minor typos in the EOSS post.
Visual check with deploy preview.

fix: correct a few minor typos in EOSS recap

---

_data/notifications.yml

Our IoT Security panel is coming up! This commit
replaces the old launch week banner with an invite
link to register for the security panel.
Checked local render of banner + link works.

chore: replace launch week with IoT security panel banner

---

_posts/2024-07-18-schematic-review-checklist.md

Fix up a few grammar and formatting errors in the checklist article.

fix: update wording and fix formatting for checklist

---

_data/notifications.yml

The banner incorrectly says 7PM CET. Fix it to say 6PM CET
Visual check

fix: adjust webiner CET time in banner

---

_posts/2024-02-01-practical_zephyr_dt.md
_posts/2024-02-15-practical_zephyr_dt_semantics.md
_posts/2024-05-16-practical_zephyr_west.md

Hi, I've checked some typos and a problem reported in one of the comments (https://community.memfault.com/u/TomP123) in the articles!

Update: Fixed typos and errors in the practical-zephyr articles

---

_posts/2024-11-07-october-2024-roundup.md

A great set of reading materials for this month.

publish: october 2024 roundup

---

_drafts/wsl2-for-firmware-development.md

Original PR here: https://github.com/memfault/interrupt/pull/515
This PR assumes that https://github.com/memfault/interrupt/pull/516 has been merged.
This part of the previous article should be updated to link to this article instead of GitHub: https://github.com/intercreate/interrupt/blob/795a1678485adfd1a07d82e0fa73282ecea0144f/_drafts/wsl2-as-a-firmware-development-environment.md?plain=1#L476-L480
JP

feat: WSL2 for Firmware Development

---

_posts/2024-12-04-december-2024-roundup.md
_posts/2024-12-04-november-2024-roundup.md

November 2024 roundup! A few tweaks from the draft:
- December -> November (year is going by so fast, but not quite that fast!)
- Add several new entries
- Adjust `pahole` article comment
Link check, visual check

publish: november 2024 roundup

---

_posts/2025-01-01-december-2024-roundup.md
readme.md

Happy New Year Interrupt 🎉 This post is scheduled for publish on 01/01.
Additionally, I added the `--future` flag to the README to show how to view future posts locally (already added to the preview deployment).

publish: merge december 2024 roundup with future publish date

---

.github/workflows/deploy.yml

Currently, we only deploy the site on pushes to `master`. This works fine expect in the cases
where we might was to schedule a post with a future publish date. This is scheduled for 10am ET every weekday.
- Manually triggered the workflow with
`gh workflow run deploy.yml --ref gminn/add-daily-deployment`,
confirmed it ran successfully ([result](https://github.com/memfault/interrupt/actions/runs/12739793493))
- Confirmed site was deployed properly 🎉

feat: add deploy workflow

---

_posts/2024-10-24-memfault-esp-component.md

We just hosted our fist interrupt live, call it out in the relevant post and add a new tag for it ✨ 
Link + visual check

chore: add interrupt live callout on esp component post

---

_posts/2025-02-20-why-sleep-for-is-broken-on-esp32.md

Interrupt live is now past, remove date and time in callout.

chore: remove time and date for esp32 interrupt live

---

_posts/2024-01-10-practical_zephyr_basics.md
_posts/2024-01-24-practical_zephyr_kconfig.md
_posts/2024-02-01-practical_zephyr_dt.md
_posts/2024-02-15-practical_zephyr_dt_semantics.md
_posts/2024-04-17-practical_zephyr_05_dt_practice.md
_posts/2024-05-16-practical_zephyr_west.md
_posts/2025-03-20-robust-ota-updates-the-easy-way.md

The latest Interrupt Live links have been added to the following posts:
- [Practical Zephyr Basics](https://interrupt.memfault.com/blog/practical-zephyr-basics)
- [Practical Zephyr Kconfig](https://interrupt.memfault.com/blog/practical-zephyr-kconfig)
- [Practical Zephyr Device Tree](https://interrupt.memfault.com/blog/practical-zephyr-device-tree)
- [Practical Zephyr Device Tree Semantics](https://interrupt.memfault.com/blog/practical-zephyr-device-tree-semantics)
- [Practical Zephyr Device Tree Practice](https://interrupt.memfault.com/blog/practical-zephyr-device-tree-practice)
- [Practical Zephyr West](https://interrupt.memfault.com/blog/practical-zephyr-west)
- [Robust OTA Updates the Easy Way](https://interrupt.memfault.com/blog/robust-ota-updates-the-easy-way)

chore: add latest Interrupt Live links

---

_posts/2025-06-20-linux-coredumps-part-3.md

This is the final part of our series on Linux coredumps! Notable
changes from the draft:
- Grammar/format fixes
- Added callout for Blake's talk next week
- Add extra footnote

publish: linux coredumps part 3

---

_posts/2025-02-14-linux-coredumps-part-1.md
_posts/2025-05-02-linux-coredumps-part-2.md
_posts/2025-06-20-linux-coredumps-part-3.md

Remove the talk blurb now that the talk has happened. The blurb now
refers to a recording, but the recordings are not yet available. Comment
it out for now while we wait for the recordings to be published.

chore: remove conference talk blurb in linux coredumps series

---

_posts/2025-02-14-linux-coredumps-part-1.md
_posts/2025-05-02-linux-coredumps-part-2.md
_posts/2025-06-20-linux-coredumps-part-3.md

Recordings from EOSS are now available! Add the link to a the coredump talk
associated with the linux coredump series.

chore: add talk recording link to Linux coredump series

---

_data/top_posts.yml
_includes/by-memfault.html
_includes/posts-nav.html
_includes/share-buttons.html
_layouts/homepage.html
_layouts/split-view.html
index.html

Readers can now see the most popular posts on the homepage. Additionally,
navigation is now available in the sidebar to jump to the latest or
top posts. A few changes accompanied this feature:
- Remove events and sandbox demo from sidebar to make room for new nav
- Replace Try Memfault with Explore Memfault in the footer "About Memfault"
with a link to the sandbox. Most readers are more likely to look at
the sandbox than fill out a form
- Add "by memfault" section to the aside in the post page
Improvements for the future:
- Add more cover images for posts -- you'll notice that some of the
older popular posts have them and they look awesome!
- Make a separate page for top posts. Currently this only exisits on the
homepage
- Scrape cloudflare dynamically for top posts instead of the current …

feat(mad): add top posts section to homepage and aside

---

_posts/2024-07-18-schematic-review-checklist.md

Per note in LinkedIn from François Baldassari, pull request for additions to the schematic review checklist, GPIO section.

Additions to the schematic review checklist, GPIO section.
