- _drafts/zero-to-main-2.md
- Update verb tense, commas, other grammatical corrections
- Add headers for each of the 4 linker script section tutorials, since I felt very surprised when the sentence "Only one more" came up. Feel free to hack these out of course
> Proofread zero-to-main 2

- _includes/footer.html
- _includes/header-custom.html
- _includes/link.html
- _sass/custom.scss
- _sass/layout.scss
- contributing.md
- Make the link more prominent
- Update "Contributing" language
- Add intake form
> Make it easier to contribute to Interrupt

- _drafts/gdb-python-post.md
- example/gdb-python-post/custom_pretty_printers.py
- example/gdb-python-post/gdb_python_post_example.c
Introduce the GDB Python API with two of my personal favorite APIs:
- pretty printers
- custom gdb commands
> GDB Python API primer

- _data/authors.yml
- _includes/header-custom.html
- _layouts/post.html
- _sass/base.scss
- _sass/custom.scss
Maybe! Thought it could be nice to give contributors more social links.
> Add social icons to `authors.yml` and display after blurb

- Gemfile
- Gemfile.lock
- _config.yml
- _drafts/armv7_mpu.md
- _includes/head.html
- _posts/2019-04-25-getting-started-with-ibdap-and-atsamd21g18.md
- _posts/2019-07-02-automate-debugging-with-gdb-python-api.md
- Add the plugin
- Verify our website with Google
- Add a description to a couple of posts
- Remove '|' character as the plugin doesn't render it anyways
and Google get's confused by it
> Add jekyll-seo-tag and add basic information

- readme.md
> Fix typo in main readme

- _sass/base.scss
- _sass/custom.scss
Let me know what you think! 
- On the home page in the list of Posts, only the highlight color is changed. 
- On a post detail page, all links are changed. 
Check out Netlify demo to see what it looks like.
> Color links in unique color

- _drafts/gdb-python-api-pypi-packages.md
- _sass/typography.scss
- example/gdb-python-pypi-post/custom_pretty_printers.py
- example/gdb-python-pypi-post/gdb_python_post_example.c
First post! Going to be proof-reading this a couple more times, but let me know if I'm blatantly missing anything or should remove things. 
This isn't the sexiest post, but is a prerequisite for more interesting GDB Python API posts and the pypi package manager post as well.
> Add GDB Python PyPi package post

- _layouts/tag.html
- _plugins/tags.rb
- _posts/2019-05-14-zero-to-main-1.md
- _posts/2019-06-25-how-to-write-linker-scripts-for-firmware.md
- _sass/layout.scss
- _sass/typography.scss
Based on https://jameshfisher.com/2019/05/05/how-can-i-add-tags-to-a-jekyll-blog/
This makes site generation a little slower, but allows us to link to post series.
> Add tags, and pages to see posts for a given tag

- _drafts/ble-throughput-primer.md
- Move discussion of new features (DPLE, 2M & Coded PHY) 
above "Auditing BLE Throughput Limiting Factors"
- Rename "Implementation Specific Details to Check" -> "Throughput Optimization Checklist" 
and add an introductory blurb to the section
- Improve description in the "Optimizing throughput Example"
- minor grammatical fixes
> Code review edits

- _posts/2019-09-24-ble-throughput-primer.md
Some great ideas of other items to mention came up in discussion on [reddit](https://www.reddit.com/r/embedded/comments/d95obo/a_practical_guide_to_ble_throughput/).
Notably,
* explicitly mention best type of GATT operations to use for throughput
* be a bit more explicit about what I meant by "link" in Reliability section
* tie fun fact about IFS spacing back to how it keeps cost downs,
making it possible for ble to be in applications that would be cost
prohibitive for other RF technologies
* also link BLE primer post in references at end of article
> Edits based on feeback from edit

- _layouts/post.html
I feel like we should be showing the names of authors more prominently on Interrupt.
> Add author name to the top of the post next to date

- _posts/2020-03-03-gnu-make-guidelines.md
Probably plenty of more of these in here 🐛🔨🔨
> Fix another typo

- _drafts/2020-03-31-march-2020-roundup.md
Didn't get a chance to write descriptions about the bottom three. Probably a good thing because there would be plenty of sass about them.
> March roundup

- _posts/2020-09-08-secure-firmware-updates-with-code-signing.md
@franc0is, I setup the wrong commit id, this repairs my repair =)
> post: fix wrong commit hash

- _posts/2019-07-09-get-the-most-out-of-the-linker-map-file.md
- _posts/2019-09-17-continuous-integration-for-firmware.md
To drive traffic to my website instead of Equisense's Medium.
> Changed URL to Continuous Delivery medium post, redirect to my website

- Gemfile
- Gemfile.lock
- _config.yml
- _posts/2019-09-17-continuous-integration-for-firmware.md
- _posts/2020-10-06-separating-unique-parameters.md
- Add gem to Gemfile
- Add plugin to jekyll
- Fix up broken links in a few posts
> Add jekyll-target-blank plugin to open links in new tabs

- _includes/share-buttons.html
For some reason, the twitter, linkedIn, and reddit social sharing icons don't work on our latest blog post. Our engineer sees this error on the post: Uncaught SyntaxError: missing ) after argument list
>  Update for the share buttons

- _posts/2019-07-02-automate-debugging-with-gdb-python-api.md
- _sass/layout.scss
Please let me know your thoughts about it.
> Improving theme

- _posts/2021-05-11-opaque-pointers.md
Fixes a bug identified in the comments of the post:
Compiled and tested the sample code this time :)
> Opaque Pointers: fix sample code bug

- _posts/2021-06-01-may-2021-roundup.md
The link was pointing to another article.
> Fix defmt blog post link

- events/index.html
> Events calendar

- _posts/2021-10-27-pre-commit.md
Minor updates, mostly typos/grammar.
> Fix a couple of typos/bad grammar, other tweaks

- _posts/2021-10-07-cmsis-packs.md
Small update to the CMSIS packs article.
> Add a section on reset info in cmsis-packs

- _includes/share-buttons.html
Update language of Featured Events sidebar.
> Update Featured Events Sidebar

- _sass/layout.scss
- js/main.js
-  the search results seemed bound to some point in the page content when scrolling;
- fixed the issue with the "scroll to see more" still appearing at the end of search;
> Fixing the scroll issue in the search bar, when the amount of results is bigger

- _posts/2022-02-01-january-2022-roundup.md
- _posts/2022-03-15-february-2022-roundup.md
- _posts/2022-04-14-march-2022-roundup.md
- _posts/2022-05-12-april-2022-roundup.md
- _posts/2022-07-19-june-2022-roundup.md
- _posts/2022-08-17-july-2022-roundup.md
- _posts/2022-09-06-august-2022-roundup.md
- _posts/2022-10-11-september-2022-roundup.md
- _posts/2022-11-01-october-2022-roundup.md
- _posts/2023-01-12-dec-2022-roundup.md
- _posts/2023-02-07-jan-2023-roundup.md
Add January roundup and relabel all 2022 roundups as 2022
> January Roundup

- _posts/2023-05-09-ota-for-embedded-linux-devices.md
merge me after May 18th - cc @bahildebrand @geekigirlx
> chore: update webinar mention to the past tense

- _posts/2023-05-24-zephyr-ring-buffers.md
Fixing a few issues found by @sarfata 😄
> fixup: Fixup issues in zephyr-ring-buffers

- _layouts/homepage.html
> Add by Memfault to header

- _posts/2023-07-12-memfault-matter.md
https://interrupt.memfault.com/blog/memfault-matter has 2 rendering issues. This change should hopefully fix those issues.
> Fix rendering issues of | in [... ]

- _posts/2019-11-20-cortex-m-hardfault-debug.md
Noticed one of my favorite external reference links moved -- fix that!
> Fix tower of terror bug link

- _posts/2023-08-16-debugging-android-devices.md
Thank you so much for your help @Blisse!
> update webinar language, 3rd time is a charm

- _posts/2023-08-30-memfault-aws-iot-expresslink.md
Fixed link in published blog post.
> Fixed link

- _posts/2023-10-04-sep-2023-roundup.md
3 things I would appreciate feedback on (bold and italics):
[**Hardware Tools for IoT Firmware Developers | by Matthias Bösl**](https://medium.com/@matthias.boesl/hardware-tools-for-iot-firmware-developers-17a98510111e)
Interrupt community member Matthias Bösl put together a helpful list of debugging tools commonly used during firmware development for those getting started on their embedded engineering journey._
_**1.  Is this too short/too newbie-focused to be included?**_ 
[**M0AGX / LB9MG - Bug of the day: missing entry point**](https://m0agx.eu/bug-of-the-day-missing-entry-point.html)
_**2.  Is this description fine?**_  
- What starts off as an adventure in debugging winds up being as simple as a missing entry point. 
Or should I do - A linker script, an `elf` file, and an entry …
> Create Sep 2023 Roundup

- _posts/2023-07-26-monitoring-battery-life.md
Added blockquote for battery metrics webinar recording with link and added blockquote for sandbox demo under the Memfault section of the article.
> Add webinar recording & URL + Sandbox demo 

- _posts/2023-11-08-device-reliability-metrics.md
> fix(typo): Device Reliability Metrics -- practices

- _drafts/elf-format-differences.md
A reference post on the difference between 32-bit and 64-bit ELF
> ELF-32 and ELF-64 Comparison Reference

- _drafts/diving-into-jtag-part4.md
Part 4 of the JTAG series.
Please take a look.
> The 4 part of Diving into JTAG

- _drafts/practical_zephyr_05_west.md
Rebase of https://github.com/memfault/interrupt/pull/413/
> Draft: Practical Zephyr part 6 "West workspaces"

- _data/notifications.yml
Memfault published a [industry benchmark report](https://memfault.com/iot-software-development-report/), so we want to
link to it for visibility!
> banner: add notification on 2024 benchmark report

- _posts/2024-05-08-eoss-recap.md
We watched a handful of talks at EOSS 2024, so we are sharing what we
learned. This is our second conference post (following EW 2024)!
Verified visually with local build.
> publish: eoss recap 2024

- _posts/2024-06-05-may-2024-roundup.md
Publish May's roundup 📚 📣
Note, the JTAG article is in drafts which is why it pops up
in the preview.
- Visual check
- Grammar check
> publish: may 2024 roundup

- _data/notifications.yml
Launch week is June 24th - 28th 🎉 . This commit adds a banner with the launch week webpage link.
Visual check + link check.
> chore: add launch week banner

- _posts/2019-07-16-fix-bugs-and-secure-firmware-with-the-mpu.md
- _posts/2019-08-20-code-size-optimization-gcc-flags.md
- _posts/2019-10-22-best-and-worst-gcc-clang-compiler-flags.md
- _posts/2019-10-30-cortex-m-rtos-context-switching.md
- _posts/2020-03-03-gnu-make-guidelines.md
- _posts/2020-05-20-arm-cortexm-with-llvm-clang.md
- _posts/2020-09-08-secure-firmware-updates-with-code-signing.md
- _posts/2021-06-22-ubsan-trap.md
- _posts/2021-10-07-cmsis-packs.md
- _posts/2022-03-30-dealing-with-large-symbol-files.md
- _posts/2023-09-20-printf-on-embedded.md
- _posts/2024-01-18-ncs-github-actions.md
```bash
❯ typos --write-changes -- $(git whatchanged --author="noah" --name-only --oneline | rg '_posts.*\.md' | sort -u | rg -v matter)
```
Manually add only the correct changes.
> Run `typos`

- _drafts/choosing_or_building_an_embedded_db.md
```bash
❯ npx prettier --write --prose-wrap=always _drafts/choosing_or_building_an_embedded_db.md
```
> Fix table formatting and run prettier

- _posts/2024-07-24-choosing-or-building-an-embedded-db.md
> content: publish embedded db

- _posts/2024-01-18-ncs-github-actions.md
- _posts/2024-08-01-github-actions-for-stm32cubeide.md
Another GH Actions article, this time for STM32CubeIDE 🧊.
Grammar pass and formatting. Bonus: add `ci` and `github-actions`
tags.
Visual check
> publish: STM32CubeIDE article

- _posts/2024-08-14-diving-into-jtag-part-6.md
A security dive concludes our JTAG series 🔒 🎉 
A few fixes:
- Grammar
- Formatting, including shrinking pictures, adjusting headers
Visual check.
> publish: JTAG part 6

- _data/notifications.yml
We have another webinar coming up -- re-add the banner with the sign up
link.
Visual check + link check
> chore: add webinar banner

- _data/notifications.yml
EW North America is fast approaching! Update the banner to point to
our meeting sign up link.
Visual check + link check.
> chore(banner): update banner for EW North America

- _data/notifications.yml
Remove the EW US banner from the site.
Visual check
> chore: remove EW US banner

- _data/notifications.yml
Add the banner for the upcoming Bond Home webinar.
> chore: add bond home webinar banner

- .devcontainer/devcontainer.json
This enables using the VSCode devcontainer extension.
> Add a devcontainer config file

- _posts/2024-12-18-wsl2-for-firmware-development.md
We have part 2 of our WSL feature ready 🎉
Visual check, links checked
> publish: wsl2 for firmware development article

- _data/authors.yml
- _posts/2025-02-20-why-sleep-for-is-broken-on-esp32.md
Publish a new article, with minor adjustments to grammar.
> publish: esp-idf sleep_for() is broken article

- _posts/2025-02-20-why-sleep-for-is-broken-on-esp32.md
Our second interrupt live event is upcoming!
> chore: add upcoming interrupt live link

- _drafts/linux-coredumps-ii.md
Adds the article going over how we reduce coredump size.
> content: add coredumps part 2 article

- _posts/2025-02-14-linux-coredumps-part-1.md
- _posts/2025-05-02-linux-coredumps-part-2.md
Part 2 of the Linux coredump series! A few minor changes for publish:
- Apply a few minor grammer + formatting changes
- Backlink to part 1
- Add link to part 2 in part 1
> publish: linux coredumps part 2

- _posts/2025-02-14-linux-coredumps-part-1.md
- _posts/2025-05-02-linux-coredumps-part-2.md
Blake is giving a talk at EOSS about building coredump collection in
Rust for Linux. Callout the talk in his coredump series!
> chore: add eoss talk callout to coredump series
